autoCorrect: true
failFast: false

test-pattern: # Configure exclusions for test sources
  active: true
  patterns: # Test file regexes
    - '.*/test.*/.*'
    - '.*/androidTest/.*'
    - '.*Tests?\.kt'
  exclude-rule-sets:
    - 'comments'
  exclude-rules:
    - 'LateinitUsage'
    - 'MagicNumber'
    - 'NamingRules'
    - 'StringLiteralDuplication'
    - 'WildcardImport'

build:
  maxIssues: 1

processors:
  active: true
  exclude:
    # For possible values check the default config:
    # https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml

console-reports:
  active: true
  exclude:
    # For possible values check the default config:
    # https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml

output-reports:
  active: true
  exclude:
    # For possible values check the default config:
    # https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  InvalidLoopCondition:
    active: true
  WrongEqualsTypeParameter:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: false
  UnreachableCode:
    active: true
  LateinitUsage:
    active: false
    excludes: "**/*Test.kt, **/*Tests.kt, **/androidTest/**, **/test/**"
    excludeAnnotatedProperties: ''
    ignoreOnClassesPattern: ''
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  UselessPostfixExpression:
    active: true

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: false
  UnnecessaryTemporaryInstantiation:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: false
    methodNames: 'toString,hashCode,equals,finalize'
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: true
    exceptions:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - IndexOutOfBoundsException
      - NullPointerException
      - RuntimeException
      - Throwable
  TooGenericExceptionThrown:
    active: true
    exceptions:
      - Error
      - Exception
      - NullPointerException
      - RuntimeException
      - Throwable
  InstanceOfCheckForException:
    active: false
  NotImplementedDeclaration:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
    exceptions: 'IllegalArgumentException,IllegalStateException,IOException'
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: false
  ThrowingExceptionFromFinally:
    active: false
  ThrowingExceptionInMain:
    active: false
  ThrowingNewInstanceOfSameException:
    active: false

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverriddenFunctions: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

complexity:
  active: true
  LongMethod:
    active: true
    excludes: "**/*Test.kt, **/*Tests.kt, **/androidTest/**, **/test/**"
    threshold: 75
  NestedBlockDepth:
    active: true
    threshold: 4
  LongParameterList:
    active: true
    threshold: 8
  LargeClass:
    active: true
    threshold: 750
  ComplexInterface:
    active: false
    threshold: 10
    includeStaticDeclarations: false
  ComplexMethod:
    active: true
    threshold: 25
  MethodOverloading:
    active: false
    threshold: 5
  TooManyFunctions:
    active: true
    thresholdInFiles: 200
    thresholdInClasses: 100
    thresholdInInterfaces: 25
    thresholdInObjects: 25
    thresholdInEnums: 15
  ComplexCondition:
    active: true
    threshold: 5
  LabeledExpression:
    active: false
  StringLiteralDuplication:
    active: false
    excludes: "**/*Test.kt, **/*Tests.kt, **/androidTest/**, **/test/**"
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'

code-smell:
  active: true
  FeatureEnvy:
    threshold: 0.5
    weight: 0.45
    base: 0.5

style:
  active: true
  ReturnCount:
    active: true
    max: 3
  ThrowsCount:
    active: true
    max: 2
  NewLineAtEndOfFile:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalWhenBraces:
    active: false
  CollapsibleIfStatements:
    active: false
  EqualsNullCall:
    active: false
  ForbiddenComment:
    active: false
    values: 'FIXME:,STOPSHIP:'
  ForbiddenImport:
    active: false
    imports: ''
  SpacingBetweenPackageAndImports:
    active: true
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 1
  MethodNameEqualsClassName:
    active: true
    ignoreOverriddenFunction: true
  ModifierOrder:
    active: true
  MagicNumber:
    active: true
    excludes: "**/*Test.kt, **/*Tests.kt, **/androidTest/**, **/test/**"
    ignoreNumbers: '-1,0,1,2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
  WildcardImport:
    active: true
    excludes: "**/*Test.kt, **/*Tests.kt, **/androidTest/**, **/test/**"
    excludeImports: >
        kotlinx.android.synthetic.*,
  SafeCast:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 100
    excludePackageStatements: true
    excludeImportStatements: true
  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  ClassNaming:
    active: true
    classPattern: '[A-Z$][a-zA-Z$0-9]*'
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z$][a-zA-Z$0-9]*$'
  FunctionNaming:
    active: true
    functionPattern: '^([a-z$][a-zA-Z$0-9]*)|(`.*`)$'
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: true
    minimumFunctionNameLength: 2
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
  ObjectPropertyNaming:
    active: true
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][A-Za-z\d]*'
    privatePropertyPattern: '(_)?[a-z][A-Za-z0-9]*'
  VariableMaxLength:
    active: false
    maximumVariableNameLength: 30
  VariableMinLength:
    active: false
    minimumVariableNameLength: 3
  ForbiddenClassName:
    active: false
    forbiddenName: ''
  ProtectedMemberInFinalClass:
    active: true
  SerialVersionUIDInSerializableClass:
    active: false
  UnnecessaryParentheses:
    active: false
  UnnecessaryInheritance:
    active: false
  UtilityClassWithPublicConstructor:
    active: false
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix: 'to'
  UseDataClass:
    active: false
  UnnecessaryAbstractClass:
    active: false
  OptionalUnit:
    active: false
  OptionalReturnKeyword:
    active: false
  ExpressionBodySyntax:
    active: false
  UnusedImports:
    active: false
  NestedClassesVisibility:
    active: false
  RedundantVisibilityModifierRule:
    active: false
  FunctionOnlyReturningConstant:
    active: false
    ignoreOverridableFunction: true
    excludedFunctions: 'describeContents'

comments:
  active: false
  excludes: "**/*Test.kt, **/*Tests.kt, **/androidTest/**, **/test/**"
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  UndocumentedPublicClass:
    active: false
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false

# *experimental feature*
# Migration rules can be defined in the same config file or a new one
migration:
  active: false
  imports:
    # your.package.Class: new.package.or.Class
    # for example:
    # io.gitlab.arturbosch.detekt.api.Rule: io.gitlab.arturbosch.detekt.rule.Rule
